AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template: Sample template that can be used to test
  EC2 updates. **WARNING** This template creates an Amazon Ec2 Instance. You
  will be billed for the AWS resources used if you create a stack from this
  template.

Resources:
  MyWebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      AdditionalInfo: This is a sample EC2 Instance
      DisableApiTermination: 'false'
      ImageId: ami-0e787554e61105680
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t2.small
      AvailabilityZone: Osaka
      Tenancy: default
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: cfn-key-1
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http to client hosts
      GroupName: MyNewSecurityGroupTemplate
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
