AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This Template will create a New EC2 with defined SecurityGroup: Sample template that can be used to test
  EC2 updates. **WARNING** This template creates an Amazon Ec2 Instance. You
  will be billed for the AWS resources used if you create a stack from this
  template.

Resources:
  MyWebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      AdditionalInfo: This is a sample EC2 Instance
      DisableApiTermination: 'false'
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t2.micro
      Tenancy: default
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: ec2-new-key
      UserData:
        Fn::Base64: |
            #!/bin/bash
            sudo yum update
            sudo yum -y install tomcat8
            service tomcat8 start
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http to client hosts
      GroupName: MyNewSecurityGroupTemplate
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0



  


